# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Geneva Hackathons
email: hello@opengeneva.org
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opengeneva.org" # the base hostname & protocol for your site
twitter_username: opengeneva
github_username:  opengeneva
port : 4001

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
